### ISSUE TITLE
Iowarp omni format

### ISSUE THREAD

**Issue by lukemartinlogan** [iowarp/content-assimilation-engine#5]
We need to define a good schema for the iowarp omni format.

```yaml
- type: POSIX
  url: /path/to/file.txt
  range: [1MB, 100MB]
  method: lazy or right now
- type: POSIX
  url: https://globus.com:/path/to/file.txt
  range: [1MB, 100MB]
  method: lazy or right now
```

How does iowarp disperse the loading of data?
E.g, on Globus, how many threads would give good performance? How many nodes?
